airalab/hs-web3

- stack.yaml
This will help hs-web3 from bitrotting on Hackage, as well as  address #1 as a side-effect as well 
See also https://docs.haskellstack.org/en/stable/yaml_configuration/?highlight=pvp-bounds#pvp-bounds
> Enable Hackage friendly stack.yaml settings

- src/Network/Ethereum/Web3/Contract.hs
This is a resubmission of #9, but using the `ReaderT` approach to preserve pattern matching.
> Change reader

- src/Network/Ethereum/Web3/Encoding/Bytes.hs
This is a simple fix to compute the correct selectors/event watchers for functions using statically sized bytestrings
> correct bytesN encoding

- src/Network/Ethereum/Web3/Types.hs
Including `null` fields causes errors when using geth.
fixes #18.
> omitting `Nothing` fields in `Call`'s JSON representation

- .travis.yml
- src/Network/Ethereum/Web3/Address.hs
- src/Network/Ethereum/Web3/Api.hs
- src/Network/Ethereum/Web3/Contract.hs
- src/Network/Ethereum/Web3/Types.hs
I want to add many more methods to make this library support the entire JSON RPC API, but first I need to get a feel for all the features of the library and ask a few questions.
Is the `INLINE` pragma useful in `Api.hs`? Does it only buy users of the library some efficiency or is necessary for some other reason? I ran a few tests and the functions seemed to work without it.
> adding a few additional RPC methods

- src/Network/Ethereum/Unit.hs
- src/Network/Ethereum/Web3/Contract.hs
- src/Network/Ethereum/Web3/Encoding/Internal.hs
- src/Network/Ethereum/Web3/TH.hs
- src/Network/Ethereum/Web3/Types.hs
- web3.cabal
fixes #24.
- updating `call` and `sendTransaction` to take `Call` argument.
- creating `Quantity` type for JSON RPC calls. See the use of `QUANTITY` in the JSON RPC docs here: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_call
+ This is better than using a Solidity type like `UInt256` because we shouldn't confuse JSON RPC types with what Solidity has available. Other EVM languages will be have different types, but JSON RPC will be for all!
POTENTIAL ADDITION: I don't think a `FromJSON` instance is necessary for `Quantity` or `Call` but TemplateHaskell yells at me if I don't include `parseJSON` for `Quantity`. I've left `Quantity`'s  `parseJSON = undefined` for now; I'll fill it in tomorrow if necessary.
code tested here: https://github.com/aupiff/hs-web3-playground/blob/86e4bf04b68d54 …
> Call argument to sendTransaction and call

- Setup.hs
Just noticed we used a `getEnv` in `Setup.hs` which can fail in some environments when `$_` isn't set to the parent process binary. This uses a safer `lookupEnv`.
> use lookupEnv instead of getEnv for non-shell-like environments

- src/Network/Ethereum/Web3/Types.hs
I'm testing the [getBlockByHash](https://hackage.haskell.org/package/web3-0.6.0.0/docs/Network-Ethereum-Web3-Eth.html#v:getBlockByHash) function against infura main net like this
```
instance Provider PublicGeth where
rpcUri = return "https://mainnet.infura.io/xxx
runWeb3' (getBlockByNumber "0x123" :: Web3 PublicGeth Block)
```
I got the following error:
```
Left (ParserFail "Error in $: When parsing the record Block of type Network.Ethereum.Web3.Types.Block the key blockNumber was not present.")
```
The reason is that [`getBlockByNumber` returns `number` instead of `blockNumber` as block number.](https://github.com/ethereum/wiki/wiki/JSON-RPC#returns-26)
Simply renaming the field of type `Block` fixes the bug.
> fix getBlockByHash and getBlockByNumber

- src/Network/Ethereum/Web3/Provider.hs
```haskell
runWeb3With :: MonadIO m => Manager -> Provider -> Web3 a -> m (Either Web3Error a)
```
Running multiple `runWeb3'` calls will create redundant managers. Users can supply their own if desired.
> runWeb3With function for user to provide Manager

- src/Network/Ethereum/Web3/TH.hs
This enables development of custom QuasiQuoters like:
```haskell
import qualified Data.Text.Lazy                       as LT
import qualified Data.Text.Lazy.Encoding              as LT
import Data.Aeson
import Language.Haskell.TH
import Language.Haskell.TH.Lib
import Language.Haskell.TH.Quote
import Network.Ethereum.Web3.JsonAbi
import Network.Ethereum.Web3.Encoding
import Network.Ethereum.Web3.TH (mkDecl, escape)
import Network.Ethereum.Web3.Address
data TruffleABI = TruffleABI ContractABI String String
instance FromJSON TruffleABI where
parseJSON = withObject "truffle" $ \t ->
TruffleABI <$>
t .: "abi" <*>
t .: "contractName" <*>
((t .: "networks") >>= (.: "4447") >>= (.: "address"))
quoteAbiTruffleDec :: String -> Q [Dec]
quoteAbiTruffleDec abi_string
= case eitherDecode abi_lbs of …
```
> TH: export mkDecl and escape

- src/Network/Ethereum/Web3/Eth.hs
- src/Network/Ethereum/Web3/Net.hs
- src/Network/Ethereum/Web3/Types.hs
The `Quantity` type is used generally for integer values in web3 json rpc.
FYI: I was prompted to make this change because I am now using `getTransactionCount` to calculate tx nonces on the branch where I'm finally implementing offline transaction signing! PR for this will come shortly.
> Updating rpc functions to use more descriptive `Quantity` type

- src/Network/Ethereum/ABI/Json.hs
- src/Network/Ethereum/Contract/TH.hs
I noticed that multiple events with the same name are not handled properly. In that case `abi` would generate conflicting data type definitions. I took a stab at fixing this myself.
> Handle overloaded events in `abi`

- src/Network/Ethereum/ABI/Prim/Address.hs
- src/Network/Ethereum/Contract/Method.hs
- src/Network/Ethereum/Web3/Provider.hs
- src/Network/Ethereum/Web3/Transaction.hs
- src/Network/JsonRpc/TinyClient.hs
- stack.yaml
- test/Network/Ethereum/Web3/Test/Utils.hs
- unit/Network/Ethereum/Web3/Test/SignatureSpec.hs
- web3.cabal
Resolves #10.
- Signing configuration requires supplying both a __private key__ and a __chainId__. The chainId will be different depending on what network a user is submitting transactions to (mainnet, Rinkby, etc.)
```haskell
-- | Web3 Provider
data Provider = Provider { jsonRpc :: JsonRpcProvider
, signingConfiguration :: Maybe SigningConfiguration
}
data SigningConfiguration = SigningConfiguration { privateKey      :: ByteString
, chainIdentifier :: Integer }
```
- The `Web3` type has been updated to have the full `Provider` type in its Reader context so that the private key and chain identifier can be used when signing transactions.
```haskell
newtype Web3 a = Web3 { unWeb3 :: ReaderT (Provider, Manager) IO a }
```
> Implementing offnode signing

- src/Network/Ethereum/ABI/Prim/Bytes.hs
- unit/Network/Ethereum/Web3/Test/EncodingSpec.hs
Using the `IsString` instance of `BytesN n` can cause an error if the provided string literal is too short, or too long. Especially for string-literals such as `"ETH" :: BytesN 8`, this behaviour is not very user friendly.
With this change too short literals are zero padded to the right. If the literal is too long, the previous 
behaviour is preserved, and an error is thrown.
> Zero-pad sized-bytes literals

- src/Network/Ethereum/ABI/Prim/Bytes.hs
- unit/Network/Ethereum/Web3/Test/EncodingSpec.hs
The [solidity specification][spec] says about the encoding of bytes (emphasis mine):
> `enc(X) = enc(k) pad_right(X)`, i.e. the number of bytes is encoded as a `uint256` followed by the actual value of `X` as a byte sequence, followed by the **minimum number of zero-bytes** such that `len(enc(X))` is a multiple of 32.
Previously, an empty bytes value would be encoded as 64 zero bytes, however, as I understand the specification, the proper encoding should be 32 zero bytes. I.e. only the 32 zero bytes for the length.
[spec]: https://solidity.readthedocs.io/en/develop/abi-spec.html#application-binary-interface-specification
Specifically, I encountered an event decoding failure on a `Transfer` event with an empty `data` field from an [ERC223 interface]( …
> Encoding of empty bytes

- src/Language/Solidity/Abi.hs
- src/Network/Ethereum/Contract/TH.hs
- test/contracts/Exchange.json
- unit/Language/Solidity/Test/AbiSpec.hs
- unit/Network/Ethereum/Contract/Test/THSpec.hs
This PR is for contracts that have `struct`s as function arguments, this is enabled in solidity files with the [ABIEncoderV2](https://solidity.readthedocs.io/en/v0.5.11/layout-of-source-files.html?highlight=abiEncoderV2#abiencoderv2). Currently, the TH fails with a parse failure.
[link for below example](https://github.com/0xProject/0x-monorepo/blob/development/contracts/exchange/contracts/src/MixinExchangeCore.sol#L90)
```Solidity
function fillOrder(
Order memory order,
uint256 takerAssetFillAmount,
bytes memory signature
)
```
> Tuple support for `pragma experimental ABIEncoderV2`

- src/Network/Ethereum/Contract/TH.hs
These cause errors of the form
Illegal data constructor name: ‘_fooData’
When splicing a TH declaration:
> Drop leading underscores in data definitions

- packages/solidity/src/Data/Solidity/Prim/Tuple/TH.hs
Had to deal with several combinations of nested reference types and ran into a couple bugs in solidity bindings.
Should be able to PR most of them in the next few days.
> Classify tuples as dynamic when a component type is dynamic

- packages/crypto/package.yaml
- packages/ethereum/package.yaml
We use nix+cabal and recent nixpkgs bring newer versions of cryptonite/vinyl. 
Doesn't seem like any of these bumps are in stackage, so not sure how to have CI test this change
> Bump some cabal upper bounds

- packages/ethereum/src/Network/Ethereum/Contract/TH.hs
- packages/solidity/src/Language/Solidity/Abi.hs
- packages/solidity/tests/Language/Solidity/Test/AbiSpec.hs
I don't see a way to distinguish `view` and `pure` with only `constant` / `payable`, so I rolled back the `funStateMutability` field to what it was since its only current use is seeing whether it's `constant`.
> Fallback to parsing 'constant' field for backwards compatibility

- packages/ethereum/src/Network/Ethereum/Contract/TH.hs
- packages/ethereum/tests/Network/Ethereum/Test/THSpec.hs
- packages/solidity/src/Language/Solidity/Abi.hs
- packages/solidity/tests/Language/Solidity/Test/AbiSpec.hs
From https://docs.soliditylang.org/en/v0.8.0/abi-spec.html#formal-specification-of-the-encoding, when any field in a struct is dynamic, so is the struct - this means that the encoding of a struct with just one field which is dynamic will be
`enc(X) = head(X(1)) tail(X(1))` which is different than the field's encoding `tail(X(1))` so we need the generated type to have the `OneTuple` wrapper.
e.g. https://github.com/airalab/hs-web3/blob/a6e726af2552e5fd2c02b8db07784f41fd939af5/packages/solidity/tests/Data/Solidity/Test/EncodingSpec.hs#L151-L155
> Fix bindings for single field structs

- packages/bignum/package.yaml
- packages/crypto/package.yaml
- packages/ethereum/package.yaml
- packages/hexstring/package.yaml
- packages/ipfs/package.yaml
- packages/jsonrpc/package.yaml
- packages/polkadot/package.yaml
- packages/provider/package.yaml
- packages/scale/package.yaml
- packages/solidity/package.yaml
- packages/web3/package.yaml
With these changes the library builds against lts-17.7 on GHC 8.10.4. Tests pass.
> Widen dependency version bounds

- .gitignore
- packages/bignum/web3-bignum.cabal
- packages/crypto/web3-crypto.cabal
- packages/ethereum/web3-ethereum.cabal
- packages/hexstring/memory-hexstring.cabal
- packages/ipfs/web3-ipfs.cabal
- packages/jsonrpc/jsonrpc-tinyclient.cabal
- packages/polkadot/web3-polkadot.cabal
- packages/provider/web3-provider.cabal
- packages/scale/scale.cabal
- packages/solidity/web3-solidity.cabal
- packages/web3/web3.cabal
This is current best practice. It also allows me to use the repo directly in `cabal.project`.
https://docs.haskellstack.org/en/stable/stack_yaml_vs_cabal_package_file/#should-i-check-in-generated-cabal-files
https://github.com/commercialhaskell/stack/issues/5210
> Add .cabal files to repo

- packages/solidity/src/Data/Solidity/Prim/List.hs
- packages/solidity/src/Language/Solidity/Abi.hs
Correctly encode and decode tuple[] data types, for example, the return
type of getMessages() below:
struct Message {
address sender;
string text;
}
function getMessages() view public returns (Message[] memory)
You can find a self-contained test case for this at the URL below. The contract is already deployed and tokens to pay fees are already there, so all you need to do is run the program.
http://45.63.90.8/~blackh/songbird.tar.gz
To build this test case:
1. expand the archive
2. cd songbird/
3. check out hs-web3
4. stack build
You can view the contract and see what the expected output of getMessages() is here:
https://songbird-explorer.flare.network/address/0x50d9799479E42f148311bFf4e00e49F60f01484f/read-contract
> Add support for Solidity error declarations.

- packages/ethereum/src/Network/Ethereum/Account.hs
- packages/ethereum/src/Network/Ethereum/Account/Class.hs
- packages/ethereum/src/Network/Ethereum/Account/Default.hs
- packages/ethereum/src/Network/Ethereum/Account/Internal.hs
- packages/ethereum/src/Network/Ethereum/Account/LocalKey.hs
- packages/ethereum/src/Network/Ethereum/Account/Personal.hs
- packages/ethereum/src/Network/Ethereum/Account/Safe.hs
- packages/ethereum/src/Network/Ethereum/Api/Types.hs
- packages/ethereum/src/Network/Ethereum/Contract.hs
- packages/ethereum/src/Network/Ethereum/Contract/TH.hs
Fixes #120. I added a new exception type, because one from System.Timeout doesn't export a constructor. This also allowed attaching transaction data to the exception, which could be useful.
> Implement transaction timeouts.

- packages/ethereum/package.yaml
- packages/ethereum/src/Network/Ethereum/Contract/TH.hs
- packages/ethereum/web3-ethereum.cabal
- packages/solidity/src/Data/Solidity/Prim/Int.hs
From the `Network.Ethereum.Contract.TH` module we can generate native ADTs to events specified on a contract ABIs. This is great if the rest of you project uses exclusively Haskell, but if you need to play along another languages or ecosystems, having a common representation such a JSON is necessary. This PR adds `ToJSON` instances for all events types (not internal `Data$` nor `Indexed$` ADTs though).
- Add missing `ToJSON` instances for `UintN` and `IntN`.
- Add aeson-casing dependency
- Add `ToJSON` instances for generated datatypes using `Generic` deriving (aeson default).
The `init'` function I use to recover the input name from the record selector of an ADT is a hack. The correct way should be to obtain that name from the `eveArgName` field on the inputs. But if I follow path, I …
> Add ToJSON instances for IntN, UintN and generated datatypes

- packages/solidity/src/Data/Solidity/Prim/List.hs
The ABI encoding for fixed length Solidity arrays `T[k]` was wrong in the case that `T` is dynamic. If T is dynamic, then according to the [spec](https://docs.soliditylang.org/en/v0.5.3/abi-spec.html#formal-specification-of-the-encoding),
> The following types are called “dynamic”:
> `T[k]` for any dynamic `T` and any `k >= 0`
This PR ensures this is the case and handles encoding for dynamic `T` similar to how it is handled in the variable length array case for `T[]` which was fixed in #126.
> Fix ABI encoding for fixed length lists

- packages/solidity/src/Data/Solidity/Prim/Tuple.hs
OneTuple becomes a pattern synonym for `Solo` above version 0.3.  This fixes the error that arises from deriving generic on the synonym.
> add cpp for OneTuple > 0.3
